//
//  CSResultInteractor.swift
//  WorkArchitecture
//
//  Created by zeero on 2020/02/03.
//  Copyright (c) 2020 zeero. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CSResultBusinessLogic {
    func doSomething(request: CSResult.Something.Request)
}

protocol CSResultDataStore {
    //var name: String { get set }
}

class CSResultInteractor: CSResultBusinessLogic, CSResultDataStore {
    
    var presenter: CSResultPresentationLogic?
    var worker: CSResultWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: CSResult.Something.Request) {
        worker = CSResultWorker()
        worker?.doSomeWork()
        
        let response = CSResult.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
