//
//  CSResultPresenter.swift
//  WorkArchitecture
//
//  Created by zeero on 2020/02/03.
//  Copyright (c) 2020 zeero. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CSResultPresentationLogic {
    func presentResult(response: CSResult.ContrastCheck.Response?)
}

class CSResultPresenter: CSResultPresentationLogic {
    
    weak var viewController: CSResultDisplayLogic?
    
    // MARK: Do something
    
    func presentResult(response: CSResult.ContrastCheck.Response?) {
        guard let response = response else {
            viewController?.showAlert(message: "取得失敗")
            return
        }
        
        let viewModel = CSResult.ContrastCheck.ViewModel(ratio: response.ratio)
        viewController?.displayResult(viewModel: viewModel)
    }
}
