//
//  CSResultViewController.swift
//  WorkArchitecture
//
//  Created by zeero on 2020/02/03.
//  Copyright (c) 2020 zeero. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CSResultDisplayLogic: class {
    func displayResult(viewModel: CSResult.ContrastCheck.ViewModel)
}

class CSResultViewController: UIViewController, CSResultDisplayLogic {
    
    var interactor: CSResultBusinessLogic?
    var router: (NSObjectProtocol & CSResultRoutingLogic & CSResultDataPassing)?
    
    
    @IBOutlet private weak var result: UILabel!
    
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = CSResultInteractor()
        let presenter = CSResultPresenter()
        let router = CSResultRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        contrastCheck()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func contrastCheck() {
        result.text = "???"
        
        let fg = router?.dataStore?.fg ?? ""
        let bg = router?.dataStore?.bg ?? ""
        let request = CSResult.ContrastCheck.Request(fg: fg, bg: bg)
        interactor?.contrastCheck(request: request)
    }
    
    func displayResult(viewModel: CSResult.ContrastCheck.ViewModel) {
        result.text = viewModel.ratio
    }
}
