//
//  CSColorCodeValidateWorker.swift
//  WorkArchitecture
//
//  Created by zeero on 2020/02/05.
//  Copyright (c) 2020 zeero. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class CSColorCodeValidateWorker {
    
    func validate(target: String) -> Bool {
        // TODO: validation
        return Int(target) != nil
    }
}
