//
//  CSContrastCheckWorker.swift
//  WorkArchitecture
//
//  Created by zeero on 2020/02/04.
//  Copyright (c) 2020 zeero. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum CSContrastCheck {
    enum GetResult {
        struct Request {
            let fg: String
            let bg: String
        }
    }
}

class CSContrastCheckWorker {
    
    func getResult(input: CSContrastCheck.GetResult.Request, callback: @escaping (ContrastCheckDataModel?) -> Void) {
        let closure: (ContrastCheckDataModel?) -> Void = { entity in
            DispatchQueue.main.async {
                callback(entity)
            }
        }
        let repository = CSWebAIMAPI()
        repository.contrastChecker(input: input, callback: closure)
//        repository.fetchResult(input: input, callback: closure)
    }
}
