//
//  CSInputViewController.swift
//  WorkArchitecture
//
//  Created by zeero on 2020/01/31.
//  Copyright (c) 2020 zeero. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CSInputDisplayLogic: class {
    func displayResult(viewModel: CSInput.ValidateColorCode.ViewModel)
}

class CSInputViewController: UIViewController, CSInputDisplayLogic {
    
    var interactor: CSInputBusinessLogic?
    var router: (NSObjectProtocol & CSInputRoutingLogic & CSInputDataPassing)?
    
    
    @IBOutlet private weak var fg: UITextField!
    @IBOutlet private weak var bg: UITextField!
    @IBOutlet private weak var button: UIButton!
    
    @IBAction private func tapped(_ sender: AnyObject) {
        validateColorCode()
    }
    
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = CSInputInteractor()
        let presenter = CSInputPresenter()
        let router = CSInputRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func validateColorCode() {
        let request = CSInput.ValidateColorCode.Request(fg: fg.text ?? "", bg: bg.text ?? "")
        interactor?.validateColorCode(request: request)
    }
    
    func displayResult(viewModel: CSInput.ValidateColorCode.ViewModel) {
        //nameTextField.text = viewModel.name
        router?.routeToCSResult(segue: nil)
    }
}
