//
//  CSInputPresenter.swift
//  WorkArchitecture
//
//  Created by zeero on 2020/01/31.
//  Copyright (c) 2020 zeero. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol CSInputPresentationLogic {
    func presentResult(response: CSInput.ValidateColorCode.Response)
}

class CSInputPresenter: CSInputPresentationLogic {
    
    weak var viewController: CSInputDisplayLogic?
    
    // MARK: Do something
    
    func presentResult(response: CSInput.ValidateColorCode.Response) {
        if response.isValidFg && response.isValidBg {
            let viewModel = CSInput.ValidateColorCode.ViewModel()
            viewController?.displayResult(viewModel: viewModel)
        } else {
            viewController?.showResult(message: "不正な入力です")
        }
    }
}
