//
//  CSInputInteractor.swift
//  WorkArchitecture
//
//  Created by zeero on 2020/01/31.
//  Copyright (c) 2020 zeero. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CSInputBusinessLogic {
    func doSomething(request: CSInput.Something.Request)
}

protocol CSInputDataStore {
    //var name: String { get set }
}

class CSInputInteractor: CSInputBusinessLogic, CSInputDataStore {
    
    var presenter: CSInputPresentationLogic?
    var worker: CSInputWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: CSInput.Something.Request) {
        worker = CSInputWorker()
        worker?.doSomeWork()
        
        let response = CSInput.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
