//
//  CSInputPresenter.swift
//  WorkArchitecture
//
//  Created by zeero on 2020/01/31.
//  Copyright (c) 2020 zeero. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CSInputPresentationLogic {
    func presentSomething(response: CSInput.Something.Response)
}

class CSInputPresenter: CSInputPresentationLogic {
    
    weak var viewController: CSInputDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: CSInput.Something.Response) {
        let viewModel = CSInput.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
