//
//  CSInputModels.swift
//  WorkArchitecture
//
//  Created by zeero on 2020/01/31.
//  Copyright (c) 2020 zeero. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum CSInput {
    // MARK: Use cases
    
    enum ValidateColorCode {
        struct Request {
            let fg: String
            let bg: String
        }
        struct Response {
            let isValidFg: Bool
            let isValidBg: Bool
        }
        struct ViewModel {
        }
    }
}
